### ISSUE TITLE
Correct your nginx config advices to be less a security risk and more performant

### ISSUE THREAD

**Issue by JanThiel** [CastosHQ/Seriously-Simple-Podcasting#131]
Hi Hugh,

on your [Help page for nignx](https://www.seriouslysimplepodcasting.com/documentation/podcast-audio-will-not-play-anywhere/#youare-on-an-nginx-server-but-not-wp-engine) you are advising to use the following nginx rules to make your plugin work. Why?
You are encouraging people to open up possible attack vectors by making .mp3 files executable with PHP. In an evil "real bad world" example someone could sneak in a prepared .mp3 file under the correct path which contains evil PHP code. That code would then be executed by the server. Security nightmare! and regularily used with images for example. This is one of the reasons why anything that might end up below /wp-content/uploads/ should never ever be allowed to be executed by PHP.
Further more you require people to add more than one location where the PHP includes are defined. This is fare from best practice and not advisable.

Why don't you advice people to simply add two rewrites to their nginx config:
```
# Seriously Simple Podcasting
rewrite podcast-download/([^/]+)/([^/]*)/? /index.php?podcast_episode=$1 break;
rewrite podcast-player/([^/]+)/([^/]*)/? /index.php?podcast_episode=$1&podcast_ref=player break;
```
No side effects, no code duplications and drop dead simple rewrites. No need to specify locations for what you want to do.

That is what I derived from the redirects you register with the WordPress routing system (https://github.com/hlashbrooke/Seriously-Simple-Podcasting/blob/master/includes/class-ssp-admin.php#L122). Works fine on our servers and feels much more right, whereas I would discourage anyone from following the suggestions in the mentioned help article.

Best Regards,

Jan

**Comment by JuanGonzalez180** [comment]
Is there any way for the "rewrite" to be configured for all domains and subdomains of the Server?

**Comment by JanThiel** [comment]
Hi @JuanGonzalez180

The rewrite directive behaves the same like the location directive. Which means you can use it below a "server" or "location" bock. Which means they are never "global". See: http://nginx.org/en/docs/http/ngx_http_rewrite_module.html#rewrite

So for what you want, you would have to configure all your sites in one server block, which I believe is no good approach.
But: You could put these rewrite rules into a separate file (e.g. podcast-rewrites.conf) and include it into all your other Config files with the server block of your single sites. 
Check out the docs: http://nginx.org/en/docs/ngx_core_module.html#include

**Comment by JuanGonzalez180** [comment]
Hello @JanThiel

I get it.
in my case, the files are generated automatically on the server, that is, when adding them in each .conf of the /vhost, the configuration can be deleted in the future.

Within the generated files there is an "include errors.conf;" I have added the 2 lines in that file for now and all domains and subdomains have worked.

Although I would like to find the nginx template file that automatically generates the .conf for each domain and subdomain. "/vhost/user__domain.com" or "/vhost/user__subdomain.domain.com" and add an "include" line.

Also, thank you very much for your help.
