### ISSUE TITLE
Adding SSP-Stats to episode front-end view

### ISSUE THREAD

**Issue by ghost** [CastosHQ/Seriously-Simple-Podcasting#134]
Over on the stats project, someone asked about adding a public dashboard.  I just wanted to be able to publish "Listens" on the front-end view of each episode.

Disclaimer: I'm not a coder, I know enough to be dangerous :)

I did write up some code to get it working - not too difficult.  Maybe someone of higher caliber wants to clean it up, optimize, and finally integrate it into a future release?  (maybe even add a switch/option so admin can enable/disable?)

in file "includes/class-ssp-frontend.php" there are 3 edits I made:

1) 
after this line (line 316)...
     `$size = get_post_meta( $episode_id , 'filesize' , true );`

Add the following paragraph:
```
// Count total entries for episode selection
if ( function_exists( 'SSP_Stats' ) ) {  //Check that the plugin is active/loaded
     global $wpdb;
     $table_name = $wpdb->prefix . "ssp_stats";
     $count_entries_sql = "SELECT * FROM $table_name WHERE post_id='$episode_id';";
     $listens_ary = $wpdb->get_results( $count_entries_sql );
     $listens = count($listens_ary);
}
```

2) 
after this:
```
if( $date_recorded ) {
        $meta['date_recorded'] = $date_recorded;
}
```

Add this:
```
// Added for listener count
if( $listens ) {
     $meta['listens'] = $listens;
}
```

3) 
In the switch($key) section, after this...
```
case 'date_recorded':
     $meta_display .= '<span class="podcast-meta-date">' . __( 'Recorded on' , 'seriously-simple-podcasting' ) . ' ' . date_i18n( get_option( 'date_format' ), strtotime( $data ) ) . '</span>';
     break;
```
Add this...
```
 // Added for listener count
case 'listens':
     $meta_display .= '<span class="podcast-meta-size">' . __( 'Listens' , 'seriously-simple-podcasting' ) . ': ' . $data . '</span>';
     break;
```

Hope this is helpful!

**Comment by whyisjake** [comment]
I would hook onto `ssp_episode_meta_details` and add this logic there. No need to modify the core plugin.
