### ISSUE TITLE
choose series image

### ISSUE THREAD

**Issue by TheCraigHewitt** [CastosHQ/Seriously-Simple-Podcasting#139]
the ability to choose an image for a series, not just for the podcast itself.

ref: https://wordpress.org/support/topic/amazing-plugin-one-major-thing-missing-images-for-series/

**Comment by kjohnson** [comment]
@TheCraigHewitt @jonathanbossenger It looks like this has already been resolved. Can you confirm?

**Comment by timnolte** [comment]
I'm currently working on this and hope to have a PR ready this weekend. I hope it's not done already.

**Comment by timnolte** [comment]
Let me know if you need any additional changes made. Thanks!
