### ISSUE TITLE
Play speed

### ISSUE THREAD

**Issue by scottwyden** [CastosHQ/Seriously-Simple-Podcasting#163]
I have a feature request. If possible, could play speed be added either in the plugin or as an addon?  Some listeners prefer playing back podcasts as 1.5x and 2.0 speeds.  So offering a simple speed option would be very useful.

**Comment by TheCraigHewitt** [comment]
Hi @scottwyden yes this type of thing is definitely on our roadmap.  Playback speed, skipping ahead/back, and some better player styling are coming soon.

**Comment by scottwyden** [comment]
Awesome!!
