### ISSUE TITLE
Podcast seasons

### ISSUE THREAD

**Issue by TheCraigHewitt** [CastosHQ/Seriously-Simple-Podcasting#167]
add functionality to include the new <itunes:seasons> feature - https://developer.apple.com/videos/play/wwdc2017/512/

**Comment by TheCraigHewitt** [comment]
update customer: info@davidweb.ca

**Comment by jonathanbossenger** [comment]
Can we have a quick chat about how to implement this on Monday?

**Comment by TheCraigHewitt** [comment]
@jonathanbossenger yep, for sure.  it's brand new from Apple so not much to go on.  it will act a lot like any of the <itunes Title>, etc type feed attributes.  Not sure on our backend how we'd set this up though.

**Comment by nickv2002** [comment]
I'd be interested in seeing support for Seasons and some of the other functionality improvements Apple has added to their Podcast spec. [Here's detailed PDF document of the additions](http://podcasts.apple.com/resources/spec/ApplePodcastsSpecUpdatesiOS11.pdf).

**Comment by TheCraigHewitt** [comment]
@nickv2002 thanks for the additional details here.  Yes we're looking at adding these to a coming release.  The details from Apple recently really helped with this.

**Comment by nickv2002** [comment]
Looks like you folks created a [solid implementation](https://www.seriouslysimplepodcasting.com/ios-11-podcast-tags/) of the new tags for seasons etc in the new version of the plugin. Thanks!

Still waiting for my podcast player of choice (Overcast) to support them but it should update soon.

**Comment by maartenhunink** [comment]
I don't see any of these features which are mention [on that page](https://castos.com/ios-11-podcast-tags/) in the current plugin, have they been removed again? Or were they never implemented? Or am I missing something?

**Comment by maartenhunink** [comment]
Ah, please ignore. I found them! There is an extra option in the settings to show those iTunes input fields.

<img width="701" alt="Screenshot 2021-08-06 at 01 55 40" src="https://user-images.githubusercontent.com/106182/128435974-329963db-c666-47cf-bbc4-592eda3c9812.png">

Which I guess means this issue could be closed?
