### ISSUE TITLE
Add shortcode parameter option to include link to episode in [podcast_playlist]

### ISSUE THREAD

**Issue by TheCraigHewitt** [CastosHQ/Seriously-Simple-Podcasting#168]
Current the [podcast_playlist] shortcode does not have the ability to view the episode post...only to play that episode in the playlist player.  We could add an icon to open the post in a new tab before the episode title.

**Comment by simondowdles** [comment]
@TheCraigHewitt - I am going to make this an optional shortcode parameter, cool?

**Comment by TheCraigHewitt** [comment]
@simondowdles yes i think it should be optional.  there's a help doc on this if you want to see how Hugh laid out the other parameters https://www.seriouslysimplepodcasting.com/doc/podcast_playlist/

**Comment by simondowdles** [comment]
Because the entire player is relying on the core media JS file with a Backbone modal and view, it is tricky to override. We will put this on ice for now as we may be overriding it with sponsored development.

**Comment by simondowdles** [comment]
@TheCraigHewitt - I am putting this task on ice until the new HTML5 player is complete.
