### ISSUE TITLE
add itunes tags to feed details

### ISSUE THREAD

**Issue by TheCraigHewitt** [CastosHQ/Seriously-Simple-Podcasting#179]
http://www.feedforall.com/itune-tutorial-tags.htm#keywords

**Comment by jonathanbossenger** [comment]
Tags per [this document ](http://podcasts.apple.com/resources/spec/ApplePodcastsSpecUpdatesiOS11.pdf)

@TheCraigHewitt I think its feasible that this could be added by the end of this week.
