### ISSUE TITLE
episode specific cover images

### ISSUE THREAD

**Issue by TheCraigHewitt** [CastosHQ/Seriously-Simple-Podcasting#180]
add ability to use the Featured Image as the podcast cover image for a particular episode

**Comment by timnolte** [comment]
Is the thought to use something other than the podcast episode featured image, which would be included in the Podcast Episode metabox? Seems pretty easy to just leverage the post types featured image and use this in the RSS.

**Comment by TheCraigHewitt** [comment]
Right on, that's great.  Thanks so much and let us know if we can do anything to help out

**Comment by timnolte** [comment]
OK, so I started to work on this and I see that the episode featured image is already used in the RSS feed for the cover art. So where would this be implemented, on the podcast listing on the website?
