### ISSUE TITLE
Modify notification text upon successfully validating API key

### ISSUE THREAD

**Issue by TheCraigHewitt** [CastosHQ/Seriously-Simple-Podcasting#185]
Currently is; Podcastmotor connect settings updated.

Should be: Seriously Simple Hosting settings updated

**Comment by jonathanbossenger** [comment]
This is tied to the tab settings, simply changing the tab name to fix this causes other issues. Can we leave this till 1.17.1?

**Comment by TheCraigHewitt** [comment]
Yes.  No problem at all.
