### ISSUE TITLE
Hide meta information

### ISSUE THREAD

**Issue by roarytubbs** [CastosHQ/Seriously-Simple-Podcasting#203]
It would be great to allow the ability in the plugin settings to show/hide podcast meta info. i.e download podcast, running time, new window.

**Comment by TheCraigHewitt** [comment]
Hi Roary, I like this one very much. We're working on an entirely new player design, and are going to make all of this optional, as well as including Subscribe buttons for iTunes, Stitcher, and Google play.  Going to give you the choice to show as much or as little as you want.  @simondowdles

**Comment by bricedupuy** [comment]
@TheCraigHewitt @jonathanbossenger what happened to the customisation? I don't see any settings for the HTML5 Player in the settings (no hooks in class-ssp-frontend.php either)
