### ISSUE TITLE
Transcript capabilities

### ISSUE THREAD

**Issue by roarytubbs** [CastosHQ/Seriously-Simple-Podcasting#204]
This might be a stretch, but enabling transcript capabilities to the plugin. Maybe even a "pro" feature...

**Comment by whyisjake** [comment]
I have some code that will do this. Not sure on the rollout, especially under the new ownership...

**Comment by jonathanbossenger** [comment]
@whyisjake feel free to submit a PR ☺️

**Comment by jonathanbossenger** [comment]
@roarytubbs you could also try out our [Seriously Simple Transcripts plugin ](https://en-za.wordpress.org/plugins/seriously-simple-transcripts/)
