### ISSUE TITLE
Apple Podcast can't show the latest RSS.

### ISSUE THREAD

**Issue by imcda** [CastosHQ/Seriously-Simple-Podcasting#208]
I find a problem, the rss code is OK, but the Podcast can't show the latest episode.

the website is: http://fromfriend.com/podcast/

the rss link is: http://fromfriend.com/feed/podcast

how to solve it?

**Comment by TheCraigHewitt** [comment]
How many posts do you have set in your Settings -> Reading area in WP?  Should be >40 for your case.  If you run into issues with this still could you comment on it in the wordpress.org support board?
