### ISSUE TITLE
compatibility issues with Simple Podcast Press

### ISSUE THREAD

**Issue by TheCraigHewitt** [CastosHQ/Seriously-Simple-Podcasting#212]
Simple Podcast Press is pulling the podcast-download file URL instead of the enclosure URL into one of their custom tables which is creating a compatiblity issue.  

They have a feature that adds a table of all episodes and links to the Episode (post) itself, but since the feed enclosure URL is different than the "audio_file" post meta it can't find a match.

**Comment by seriouspodcaster** [comment]
@TheCraigHewitt Could Simple Podcast Press perhaps organize a temporary demo account for us to debug this further?

**Comment by seriouspodcaster** [comment]
The plugin by default uses the 'enclosure' post meta key to make use of the 'download URL' which allows the plugin to then track usage on that episode. 

Adding in the below code will ensure that the URL to the audio file is served directly instead:

```
add_filter( 'ssp_feed_item_enclosure', 'ssp_change_feed_enclosure', 10, 2 );

function ssp_change_feed_enclosure( $enclosure, $podcast_id ){

	$audio = get_post_meta( $podcast_id, 'audio_file', true );

	if( $audio !== "" ){
		return $audio;
	}

	return $enclosure;

}
```
