### ISSUE TITLE
Ability to import/export podcasts

### ISSUE THREAD

**Issue by seriouspodcaster** [CastosHQ/Seriously-Simple-Podcasting#216]
Either based on a CSV or XML file to move data between sites

**Comment by timnolte** [comment]
Seems like this might be accomplished by simply dumping an XML file in the standard RSS format, containing the full library of course. Not quite sure if RSS supports embedded files though. You thinking an export/import would include the a actual podcast episode files or just references to them, like in an RSS feed?
