### ISSUE TITLE
Indicate if an extension is already installed

### ISSUE THREAD

**Issue by hlashbrooke** [CastosHQ/Seriously-Simple-Podcasting#229]
On the SSP 'Extensions' page in the WP dashboard, the extensions all have a 'Get this Extension' button. Clicking the button open up the plugin details modal with an option to install the  plugin from there. If the plugin is already installed, however, then the 'Get this Extension' button is still there - the only difference is that the plugin details modal has the install button disabled with the text 'Latest Version Installed'.

It would be great if the extension listing page would indicate if the extension is already installed or not. That should be a fairly simple check to see if it is there and I think it would make things a little less confusing on that page.

**Comment by TheCraigHewitt** [comment]
@hlashbrooke good call....we'll look into this for a coming release.  Thanks as always!
