### ISSUE TITLE
Assigning episodes to multiple series

### ISSUE THREAD

**Issue by jonathanbossenger** [CastosHQ/Seriously-Simple-Podcasting#234]
It should not be possible to assign an episode to multiple series.

**Comment by hlashbrooke** [comment]
And why not? Not trolling here - genuinely curious as I quite liked the ability to do that. I'm not really a serious podcaster though, so my use case for this plugin isn't like the 'average' user of course.

**Comment by whyisjake** [comment]
This is a major use case for us at WIRED too.

**Comment by jonathanbossenger** [comment]
Ok good to know and one of the reasons I logged the issue first. Thanks

@TheCraigHewitt some food for thought.

**Comment by TheCraigHewitt** [comment]
@whyisjake so you would like to keep the ability to have a single episode be a part of multiple series?

**Comment by whyisjake** [comment]
Yeah, we have a feed that includes all episodes from all series. This is an opt-in, rather then opt-out.
