### ISSUE TITLE
RSS feed authentication using WP capabilities

### ISSUE THREAD

**Issue by lpcollier** [CastosHQ/Seriously-Simple-Podcasting#237]
I've written a simple function to authenticate RSS feeds based on user capabilities. I may develop this into a proper plugin - time permitting - but I thought I would offer it here first as I haven't been able to find a similar solution out there. At the moment I'm using it in a basic plugin file with no configuration UI.

A user can only access the RSS feed (and hence a podcast feed) if they have the capability feed_feedname. This means that any of the many membership type plugins that manage capabilities can be used to grant or deny access to individual feeds rather than the current blanket password used in SSP.

If the user is not logged in, it will present an HTTP auth login box. It will accept username or email address for login purposes. It works with iTunes and the iPhone podcasts app, I haven't personally tested it with other apps/devices but 200-odd podcast subscribers haven't complained since I switched to this system and turned off the global password in SSP.

```php
function lpc_check_feed_auth() {
	if (is_user_logged_in()) {
		if(current_user_can('feed_'.str_replace('-','_',end(explode('/',substr(get_current_page_url(),0,-1)))))) {
			return;
		}
		else {
			echo ">\r\rRSS Feeds Authentication LP Collier 2017";
			echo "\r\rUser not authorised for this feed";
			exit;
		}
	}
	 if (!isset($_SERVER['PHP_AUTH_USER']) && (isset($_SERVER['HTTP_AUTHORIZATION']) || isset($_SERVER['REDIRECT_HTTP_AUTHORIZATION']))) {
        if (isset($_SERVER['HTTP_AUTHORIZATION'])) {
            $header = $_SERVER['HTTP_AUTHORIZATION'];
        } else {
            $header = $_SERVER['REDIRECT_HTTP_AUTHORIZATION'];
        }

        list($_SERVER['PHP_AUTH_USER'], $_SERVER['PHP_AUTH_PW']) = explode(':', base64_decode(substr($header, 6)));
    }
	
    if (!isset($_SERVER['PHP_AUTH_USER'])) {
        header('WWW-Authenticate: Basic realm="RSS Feeds"');
        header('HTTP/1.0 401 Unauthorized');
        echo '\n\nFeeds from this site are private';
        exit;
    } else {
		$myid=$_SERVER['PHP_AUTH_USER'];
		$mypass=$_SERVER['PHP_AUTH_PW'];
		if (strpos($myid, '@') !== false) {
			/* replace email address */
			if (get_user_by('email', $myid) !== false)
				$myid=get_user_by('email', $myid);
		}
        if (is_wp_error(wp_authenticate($myid,$mypass))) {
            header('WWW-Authenticate: Basic realm="RSS Feeds"');
            header('HTTP/1.0 401 Unauthorized');
	    echo ">\r\rRSS Feeds Authentication LP Collier 2017";
            echo "\r\rUsername and password were not correct";
            exit;
        }
    }
}

add_action('rss2_ns', 'lpc_check_feed_auth', 1);
```

It requires the same .htaccess rewrite rule as the SPP password system:

```
RewriteRule . /index.php [E=HTTP_AUTHORIZATION:%{HTTP:Authorization},L]
```

At some point it needs updating to use HTTP Digest to improve the security a bit.

**Comment by whyisjake** [comment]
I'm not owner of this plugin, but I have had a bee in my bonnet to accomplish something similar to this. The hard thing about doing any kind of authentication scheme with feeds, is that the feedcatcher, iTunes/Overcast/Castro/etc will need to find someway to authenticate against the feed. 

This plugin, as currently authored assumes that the host service is running Apache, and would then fail for any other type of server. 

The solution that I'd like to work to, either as a core part of SSP, or as a standalone plugin would be creating a key/value system for the feed that is both anonymous, and has an expiration path. So, as part of a users account, they would have a personalized feed. Something like `site.com/feed/podcast/?userkey=somethinganonymousandlong`. The feed would then authenticate against that feed, ensure that the key matches a specific user, ensures that the user has the specific privs, and then serves the feed. 

This gets around the authentication issue, allowing any feedcatcher to work without having to authenticate. This lacks the security of a specific feed being tied to a user, and the keys could be shared, but I think it leads to a better experience for the user. (This is something similar to what Patreon does...)

**Comment by lpcollier** [comment]
Thanks - yes I did think about the key/value approach, my concern was compatibility with smartphone podcast apps, because the approach you describe would involved logging into the website to refresh the key, I think. The HTTP Auth approach is widely supported by podcast apps and it's easy for the user to log in when it pops up the message.

You're right that I've only tested this with Apache, but why do you think that it would only work with Apache? My understanding is that HTTP Auth is part of HTTP which all servers should support. There is info for getting it to work with IIS here: http://php.net/manual/en/features.http-auth.php and with Nginx here: https://serverfault.com/questions/520647/how-to-get-php-auth-user-and-php-auth-pw-available-in-nginx and the basic setup is already used in SSP, but with a global password rather than a per-feed user capability check as described here.
