### ISSUE TITLE
Add tooltip or docs link to iTunes fields setting

### ISSUE THREAD

**Issue by hlashbrooke** [CastosHQ/Seriously-Simple-Podcasting#301]
The setting labelled "Enable iTunes fields" adds fields for iOS specific data to the episode details. As a podcast maintainer who doesn't really know what that's all about, it looks like it should be important, but I don't know how it works. Adding a tooltip or just a basic link to your documentation about it would be a huge help.

After chatting with @jonathanbossenger I see that I don't need to worry about that for the podcast that Ii'm managing, but most people don't have direct access to the plugin dev :)

**Comment by TheCraigHewitt** [comment]
Hey @hlashbrooke great call.  A few tooltips are things that we've had in mind in the plugin, so this would be a smart first step in that direction.  Thanks!
