### ISSUE TITLE
new_image_data_array : Undefined variable

### ISSUE THREAD

**Issue by ebadmail** [CastosHQ/Seriously-Simple-Podcasting#324]
Could you initialize this variable or remove it when its empty?

Notice: Undefined variable: new_image_data_array in /home/sitesworldvision/public_html/website/wp-content/plugins/seriously-simple-podcasting/includes/class-ssp-frontend.php on line 487

Thanks.

**Comment by jonathanbossenger** [comment]
Thanks @ebadmail I have issued a PR to fix the issue and will merge this into the next plugin release.
