### ISSUE TITLE
Other (non-podcast) post types don't show up on series archives

### ISSUE THREAD

**Issue by mallardduck** [CastosHQ/Seriously-Simple-Podcasting#341]
As suggested in #340 this issue is to track a bug mentioned there. (Note: this isn't an issue that affects my use case, just one I discovered)

The issue occurs when you add support for the SSP `series` taxonomy on other post types. It shouldn't matter if this is a built-in or custom post type - both appear affected. To closely replicate the environment I discovered this in a CPT should register `series` as a supported taxonomy. After creating a series and only including posts from this CPT the archive page will show "Nothing Found".

**Comment by jonathanbossenger** [comment]
@mallardduck version 1.20.3 of the plugin included better support for the series taxonomy, could you please check if this update resolves this issue. Thanks

**Comment by mallardduck** [comment]
@jonathanbossenger 
Hi, I'm not seeing a 1.20.3 - updated to 1.20.2 though. However I'm not sure how to properly test this at this point. Unfortuneately a few things happened since I originally reported that make this hard for me to test.

First, I essentially solved the problem by making my own "Issue" taxonomy; since Series or Issue would fit just as well for my use case. So in order to not mess with the Podcast's Series, I opted to simply use a different term/key.

Secondly, the Podcast website project I was working on is no longer in use. (Got shut-down by an IT team not familiar with WP) So it's been a few months since that project was active and I'm not fully sure how to test this any more.

However, I did update the project and plugins to try and test things out. I've not been able to successfully test this. I have been able to add the Series taxonomy this plugin provides to a post - however after doing so it only shows the Post types, not Podcast types, in the archive.

While this could indicate it isn't resolved, I'm not confident in the environment - since the project was DOA and hasn't been touched in a few months..

**Comment by jonathanbossenger** [comment]
@mallardduck sorry, I meant 1.20.2, not 1.20.3. That being said 1.20.3 was shipped this morning, with other updates.

The fixes that shipped with 1.20.2 where updates specifically related to the series taxonomy, in some cases we noticed that the series taxonomy was not being attached to custom post types marked to be included as podcasts. 

However on reading your description above I think that what you're expecting it to do is show all post types attached to a specific series, when you view the series archive. I will perform my own test against 1.20.3 and let you know.

**Comment by mallardduck** [comment]
>  show all post types attached to a specific series, when you view the series archive

That's exactly it! From the test I did on that old project that didn't seem to be the case yet.
