### ISSUE TITLE
Simple and clean front page

### ISSUE THREAD

**Issue by extremeweather1** [CastosHQ/Seriously-Simple-Podcasting#392]
I was ask to post this from the WP support forum.

Hello and thank you for the opportunity to post a question here. At the risk of sounding like a newbie, we are trying to accomplish the following;

We would like to accomplish something similar to our podcast pages on other platforms (i.e.) Apple Podcast and Google Podcast but on our own domain. I am including the links below:

https://podcasts.apple.com/us/podcast/xw-noaa-severe-weather-alerts/id1473245652

https://podcasts.google.com/?feed=aHR0cHM6Ly9hbmNob3IuZm0vcy9jYzRiMThjL3BvZGNhc3QvcnNz

with a similar look, feel and functionality. In short, Simple and Clean…

Needless to say, after installing your add-on as well as after several attempts we have failed miserably. Can you or anyone else in your community lead us in a direction to accomplish our goals.

At this time, We host our podcast Anchor but are listed on an additional 12 platforms and would like to offer the same on our own domain.

Our current website / domain is located at:

https://podcast.xtremeweather.org

We are a non-profit and $$$ are always an issue, so please help.

Thank you,
podcast@xtremeweather.org

**Comment by jonathanbossenger** [comment]
Hello @extremeweather1 would something link this work for you?

https://wphackercast.com/podcast-2/
