### ISSUE TITLE
Create a setting the limit the number of items displayed on a widget

### ISSUE THREAD

**Issue by lordneeko** [CastosHQ/Seriously-Simple-Podcasting#396]
Please add a setting to the widgets to set how many episodes to display on a widget. Example: the series widget will currently show ALL episodes...which could be over a hundred in an ongoing series. Create a box where I can set the most recent # of episodes

**Comment by TheCraigHewitt** [comment]
hi @lordneeko thanks for the suggestion.  We'll be adding this to our development queue here in the near future.

**Comment by lordneeko** [comment]
thanks! love this plugin.it's simple and easy to use and provides good functions

**Comment by lordneeko** [comment]
Any updates on when 1.21.0 might get created? I haven't updated the plugin in a while because I don't want to keep having to re-fix this.

**Comment by jonathanbossenger** [comment]
@lordneeko I am busy with a round of plugin updates this week, so I am planning on including this with those updates.

**Comment by lordneeko** [comment]
Great thanks

**Comment by lordneeko** [comment]
Hello this was a year ago. I'm still having to manually fix this every time you post an update.

Are you ever going to do this one? You said it would be 1.21, but now we're on 2.1.1

**Comment by jonathanbossenger** [comment]
@lordneeko thanks for bumping this, it fell off our radar. I'm actively working on the next plugin update and I will add this to that list and make sure it's included.

**Comment by jonathanbossenger** [comment]
@lordneeko this will be included in the next plugin release. As the playlist and recent episodes widgets already have the ability to limit episodes, the series widget now also includes that option.

**Comment by lordneeko** [comment]
haha! Thanks for the shout out in the release notes.
