### ISSUE TITLE
Use context in ssp_episodes() caching

### ISSUE THREAD

**Issue by JiveDig** [CastosHQ/Seriously-Simple-Podcasting#397]
I'm building a custom shortcode/block that uses `ssp_episodes()` directly. I'm also using `ssp_episode_query_args` filter to change the query args based on a custom context passed to `ssp_episodes()`. The problem is that it seems my filter would either be applied to all calls to `ssp_episodes()` or it would be unused if the transient is already set.

I think when building the cache key it should utilize the `$context` too, like this:
```
$key   = 'episodes_' . $series . '_' . $context;
```
Or more fully:
```
// Do we have anything in the cache here?
$key   = 'episodes_' . $series . '_' . $context;
$group = 'ssp';
$posts = wp_cache_get( $key, $group );
// If nothing in cache then fetch episodes again and store in cache
if ( false === $posts ) {
	$posts = get_posts( $args );
	wp_cache_add( $key, $posts, $group, HOUR_IN_SECONDS * 12 );
}
```
Hope this makes sense.

My worry is that any uses of `ssp_episode_query_args` filter or `$context` arg will not be getting the expected results.

Thanks for looking ;)

**Comment by jonathanbossenger** [comment]
@JiveDig the only possible downside to using the $context variable as part of the cache key, would be that you'd end up with multiple cached versions of the episodes, eg one for the front end archive page, one for the RSS feed, one for one of the episode related shortcodes (if it's being used) etc.

What might work better is if you took the code of the  ssp_episodes() function as is, and used it to make your own custom function, that replicates what you like about the ssp_episodes() functionality, but is more custom to your needs. That way you'll still be making use of the ssp_episode_ids() and ssp_post_types() functionality, but you can control the arguments passed to the query and set your own cache transient.
