### ISSUE TITLE
Missing Dependencies 	ssp-html5-player

### ISSUE THREAD

**Issue by JiveDig** [CastosHQ/Seriously-Simple-Podcasting#399]
From Query Monitor:
![Screenshot 2019-08-13 19 45 06](https://user-images.githubusercontent.com/540990/62985348-eacd9900-be04-11e9-8a49-5a5c351dc6e8.png)

I've been seeing this on a few sites we use SSP on but can't seem to find the source.

Wondering if anyone else has seen this.

**Comment by JiveDig** [comment]
Actually on this site it seems to be related to using `$ss_podcasting->episode_meta( $episode_id );` to show the player.

**Comment by jonathanbossenger** [comment]
@JiveDig thanks for bringing this to our attention, I was not aware of this issue and I will make sure we get it fixed in the next release.
