### ISSUE TITLE
Gizmo icon font overriding Divi icon fonts

### ISSUE THREAD

**Issue by contemplate** [CastosHQ/Seriously-Simple-Podcasting#402]
We load the recent podcast in an HTML5 player on many pages of our site but it then changes the icon font used for any Divi module that uses an icon on that page.

HTML Example:
`<span class="et_overlay et_pb_inline_icon" data-icon=""></span>`

CSS:
`
[data-icon]::before {

    font-family: "gizmo" !important;
    content: attr(data-icon);
    font-style: normal !important;
    font-weight: normal !important;
    font-variant: normal !important;
    text-transform: none !important;
    speak: none;
    line-height: 1;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;

}

.... other styles .....

.et-pb-arrow-prev::before, .et-pb-arrow-next::before, .et_pb_testimonial::before, .et_pb_toggle_title::before, .et_overlay::before, #et_search_icon::before, .mobile_menu_bar::before, .et-social-icon a::before, .et_pb_social_icon a.icon::before, .et_pb_font_icon::before, .et_audio_container .mejs-playpause-button button::before, .et_audio_container .mejs-volume-button button::before, #et-info-phone::before, #et-info-email::before, .et-cart-info span::before, .et_pb_pricing_table_button::after, .et_pb_promo_button::after, a.et_pb_more_button::after, .et_pb_newsletter_button::after, .comment-reply-link::after, .form-submit .et_pb_button::after, .et_pb_contact_submit::after, .et_pb_contact_reset::after, .et_password_protected_form .et_submit_button::after, .et_pb_button::after, .woocommerce button.single_add_to_cart_button.button::after, .woocommerce a.button.alt::after, .woocommerce-page a.button.alt::after, .woocommerce button.button.alt::after, .woocommerce-page button.button.alt::after, .woocommerce input.button.alt::after, .woocommerce-page input.button.alt::after, .woocommerce #respond input#submit.alt::after, .woocommerce-page #respond input#submit.alt::after, .woocommerce #content input.button.alt::after, .woocommerce-page #content input.button.alt::after, .woocommerce-page a.button::after, .woocommerce button.button::after, .woocommerce-page button.button::after, .woocommerce input.button::after, .woocommerce-page input.button::after, .woocommerce #respond input#submit::after, .woocommerce-page #respond input#submit::after, .woocommerce #content input.button::after, .woocommerce-page #content input.button::after {

    text-shadow: 0 0;
    font-family: "ETmodules" !important;
    font-weight: normal;
    font-style: normal;
    font-variant: normal;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
    line-height: 1;
    text-transform: none;
    speak: none;

}

`

**Comment by James-Steward** [comment]
I also have the same issue on my site. I’ve currently by passed the issue by adding “. ssp-player“ before the CSS selector below:
`[class^="icon-"]:before,
[class*=" icon-"]:before {
  font-family: "gizmo" !important;
  font-style: normal !important;
  font-weight: normal !important;
  font-variant: normal !important;
  text-transform: none !important;
  speak: none;
  line-height: 1;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
} `

**Comment by jonathanbossenger** [comment]
Thanks @contemplate and @James-Steward, we will be including this in our next release.

**Comment by jonathanbossenger** [comment]
@contemplate @James-Steward in order to debug and fix this issue, could I ask, how are you adding the html5 player to a Divi built post or page?

**Comment by TheCraigHewitt** [comment]
This is the WordPress.org thread around the issue: https://wordpress.org/support/topic/fontawesome-gizmo-font-conflict-2/ - I asked for examples of where users are seeing this on their sites so we can better troubleshoot.
