### ISSUE TITLE
Episode full description not showing in RSS Feed

### ISSUE THREAD

**Issue by jonathanbossenger** [CastosHQ/Seriously-Simple-Podcasting#411]
Under certain circumstances, the description is not showing.

**Comment by eliasgomezsainz** [comment]
I have this problem:

- My settings: https://imgur.com/a/U3qgDkA
- My feed: https://negocioswp.es/feed/podcast/
- Even I have “Full Content” in Settings > Reading > RSS content.
- I've removed the style and I don't see any change: `add_filter( 'ssp_enable_rss_stylesheet', '__return_false' );`
- The content in the feed is way shorter than the real content

**Comment by asivo** [comment]
Having the same problem for a very long time now. Descriptions get cut off after 55 Words.

- Feed: http://guteslauchgefuehl.de/feed/podcast/ein-gutes-lauchgefuehl

**Comment by Robmanzzz** [comment]
> Having the same problem for a very long time now. Descriptions get cut off after 55 Words. iTunes shows the full description though.
> 
> * Feed: http://guteslauchgefuehl.de/feed/podcast/ein-gutes-lauchgefuehl

Hi Asivo. I opened your feed and noticed that you got around the 55-word limit. Care to share? :)

**Comment by asivo** [comment]
Yes sure. Copy your episode description into the excerpt box. That‘s it. This should’ve been fixed a long time ago.

**Comment by eliasgomezsainz** [comment]
Still not working :(
