### ISSUE TITLE
resolving issues with 'google podcasts' compliance

### ISSUE THREAD

**Issue by anotherstuart** [CastosHQ/Seriously-Simple-Podcasting#419]
At the moment Seriously-Simple-Podcasting adds a general link to the podcast RSS on every page as the last thing in the <head> section: 
`<link rel="alternate" type="application/rss+xml" title="Podcast RSS feed" href="http://www.strategyandevidence.com/feed/podcast" />`

and on the podcast page itself it adds an extra specific one
`<link rel="alternate" type="application/rss+xml" title="Strategy and Evidence &raquo; Podcast Feed" href="http://www.strategyandevidence.com/podcast/feed/" />`
this one is almost at the top of the <head> section, with the other RSS feeds

The RSS that is created by the plugin seems to be right - but it is important to note (for the rest of the job) that the 'link' it has (conforming with google podcasts info) is for the site root homepage (in my case www.strategyandevidence.com) - this can be right - or perhaps it needs to be the podcast page itself. This depends ... 

**The only two things that really matter here (in terms of google podcasts) are that the page given as the link in the podcast RSS has one and one only 'alternate' RSS link and that is properly to the podcast - with the correct podcast title [I think that may be important]**

Problem 1: the 'alternate' link on every page doesn't have the a real podcast title, just a generic one

Problem 2: the specific 'alternate' link on podcast page has the right title, but there are 2 (the general one that appears on every page, and the  on that page, which google doesn't like

Problem 3: I am not honestly sure whether the homepage in the feed should be the 'root homepage' of the site or the 'podcast homepage'

Problem 4: the RSS feeds for 'blogs' and 'comments' that wordpress puts on every page violate the google guidelines of the only 'alternate' link being for the podcast. There is a simple way external to your plugin to stop this happening that I have found, but I think that this should be built in as an option to the plugin.

I am searching the code for how this can be quickly and easily fixed; but it's tricky and not my core skill ; ) Any help welcome. Unfortunately I don't even know where or how to "put in a filter" - but I am pretty quick on the uptake.

Thanks

**Comment by anotherstuart** [comment]
Having thought about this and implemented the code to get rid of the non-podcast RSS 'alternate' links on my root homepage I think that , in terms of compliance.

1) the only 'alternate' link for RSS that appears on the root home page is for the podcast RSSfeed
2) the <link> in the podcast RSS feed points at the root homepage
so that is 2 ticks!
but
3) The podcast title on the 'alternate' RSS link in the root homepage is different to the title in the RSS podcast feed. Because on the homepage it is a generic title of 
`title="Podcast RSS feed"`
yet in the RSS feed it is listed as 
`<title>Strategy and Evidence</title>`

which would be nice to resolve - as we don't know how strict google podcasts is about this.

All the other stuff is about options for where people want their podcasts 'homepage' to be if not the root homepage of the site - which will be important for people with multiple series - which is a great feature of this plugin; so could be really great to get fixed.

**Comment by jonathanbossenger** [comment]
@anotherstuart thanks for the info, and the update. Can I confirm that you've been able to use the available filters to make it work for your requirements?

@TheCraigHewitt we might need to discuss this one. If there are a specific set of requirements for Google Podcasts.

**Comment by anotherstuart** [comment]
@jonathanbossenger thanks for the reply... I didn't use filters (as I still haven;t learnt how to!) but I have managed what I think is a valid workaround for this one case by

1) using information [here](https://stackoverflow.com/questions/34750148/how-to-delete-remove-wordpress-feed-urls-in-header)  to remove all other wordpress inserted 'alternate' RSS feeds on my site
and
2) being satisfied that it's OK for my root home page to be used as my podcast home page (I only have one podcast series on this site)

but that leaves me with the nagging doubt over whether the podcast title in the podcast RSS feed being different to the one in the cross-site generic 'alternate' link is a problem or not. 

So for me, in this one case, the priority is to change the podcast title in the generic site-wide link inserted by your plugin

But for people with more than one series per site (which could be me really soon) all the other issues have to be addressed - and i have to know where and how to insert the code to activiate the filters!!! (my problem)

**Comment by jonathanbossenger** [comment]
Thanks @anotherstuart we'll review this information and look into how to best implement this change, without breaking users sites.

**Comment by anotherstuart** [comment]
Thanks! This is an interesting experience (!)

To update you, my podcast is now showing on google podcasts (both on the web and in their app) so my workaround must have worked and so I reckon worth fixing to make that easier for others (and the issue with different series on one site).

However - now I am listed I have hit another (compliance?) problem which is that my podcast appears completely correctly but is not playing or downloading via google podcasts. The behaviour of google trying to play it mirrors the problem listed on the wordpress-plugin forum here: https://wordpress.org/support/topic/google-podcasts-app-problem/

But the solution is not useful as none of my site (where the site, rss and mp3 is hosted) are on https.

I may rasie anything that goes on over there over here if it looks like a programming issue.

But for now - solved on the feed/webpage tags issue.

Thanks!
