### ISSUE TITLE
PHP 7.4

### ISSUE THREAD

**Issue by cjstone** [CastosHQ/Seriously-Simple-Podcasting#436]
We’ve upgraded to php 7.4 and are now seeing this error (3 similar lines):

`Trying to access array offset on value of type bool in /mnt/wordpress/wp-content/plugins/seriously-simple-podcasting/php/includes/ssp-functions.php on line 870`

Everything else seems to be working OK, but we’re a little concerned about the error.
Thanks,

CJS

**Comment by jonathanbossenger** [comment]
https://make.wordpress.org/core/2020/08/13/wordpress-5-6-release-planning/

We should also make sure the plugin supports PHP 8 by the time 5.6 is released.
