### ISSUE TITLE
The 'ssp_episode_image' filter doesn't effect the episode image

### ISSUE THREAD

**Issue by maartenhunink** [CastosHQ/Seriously-Simple-Podcasting#442]
When using the `ssp_episode_image` filter to change the image of an episode, the actual episode image in the rss feed is not effected. 

Instead I discovered there is also the `ssp_feed_item_image` filter, through which it **is** possible to alter the image of the episode. 

It could be helpful to add this filter to the [documentation](https://support.castos.com/article/70-filter-reference) and possibly explain the difference between the two filters.

**Comment by jonathanbossenger** [comment]
@jonathanbossenger add this to the documentation
