### ISSUE TITLE
Addon plugins (Speakers and Stats) appear to have stopped working

### ISSUE THREAD

**Issue by fienen** [CastosHQ/Seriously-Simple-Podcasting#487]
**Describe the bug**
After a recent update to 2.0.4, and subsequently 2.1.1, it appears that the Seriously Simple Speakers and Stats plugins are no longer showing up in the UI when installed and activated.

**To Reproduce**
1. Install and activate SSP
2. Install and activate SSSpeakers
3. Install and activate SSStats
4. No Speakers taxonomy is available in the menu or in podcast posts
5. No Stats link is available in the menu, and no dashboard widget is available

**Expected behavior**
Issues 4 and 5 above should be true conditions.

**Additional context**
I know this could be more a problem with the other two plugins rather than the core plugin depending on where the hook problems are. Since both appeared to stop working at the same time, I made the assumption that something in the core plugin changed that decoupled the support.

**Comment by jonathanbossenger** [comment]
Hi @fienen 

I've tested installing both plugins on a development site, and things still work as expected (see video https://cloudup.com/ciejqrHq2od)

Nothing in any of the 2.x releases should have affected the loading of either of the plugins.

However, if you're able to set up a test/development site with the plugins active, but not loading, I could take a look and see if anything has been affected.

**Comment by jonathanbossenger** [comment]
@fienen quick update here, while I can't replicate this on my current podcast site, I am seeing it on my development site, as I'm testing the upcoming 2.2.0 release. So I will see what is causing the problem there, as it might be related.

**Comment by jonathanbossenger** [comment]
@fienen so the reason this breaks on my development site, is that I am using the GitHub Updater, and loading the plugin files from our GitHub Repository. Are you installing the plugin in a similar way (ie from a GitHub resource) or from the official WordPress.org repository. If so, this might explain why it's not working for you.

**Comment by fienen** [comment]
I'll doublecheck. I do use GitHub Updater for stuff like my theme code, but I don't think I was using it for these plugins. I could be wrong though. I'll take a look and confirm that I'm loading it from the WP repo and not directly from GitHub and get back to you.
