### ISSUE TITLE
Add a "latest episode" option to the player block

### ISSUE THREAD

**Issue by hlashbrooke** [CastosHQ/Seriously-Simple-Podcasting#491]
The new player block is awesome. It would be great if there was an option (perhaps the default), was to always show whatever the current latest episode is, but still allow people to select whichever specific episode they want.

**Comment by jonathanbossenger** [comment]
@hlashbrooke thanks for this.

Does the drop down not always default to the latest episode? Or do you mean when it loads the block, it loads the latest episode and displays the player, and then only if you edit it you'd need to choose a different episode?

**Comment by hlashbrooke** [comment]
I mean that when the block is loaded on the frontend, it will load whatever the current latest episode is. Like in the "Latest Sermon" area here: https://www.southerncrosschurch.org/sermons/ - that's dynamic and will show the latest sermon that has been added to the site and the time you load the page.
