### ISSUE TITLE
Why does the "ssp_readfile_chunked" function exist?

### ISSUE THREAD

**Issue by theGrue** [CastosHQ/Seriously-Simple-Podcasting#497]
**Describe the bug**
When a user (or bot) clicks the "Download file" link in the blog post, a special "?ref=download" query parameter is appended to the URL. This triggers a special path in the code that (if `allow_url_fopen` is enabled on the server) downloads the file to the web server first, then sends it to the downloader, rather than sending a 302 redirect as would happen if "?ref=download" were not part of the URL.

**To Reproduce**
1. Go to any podcast episode post.
2. Click on "Download file"

**Expected behavior**
I don't expect an obscure feature to allow the Googlebot and others to suck up my monthly bandwidth while no user would ever care about or need this feature.

**Additional context**
I recently had to migrate from a web server that had `allow_url_fopen` off to a web server that has `allow_url_fopen` on. This unnoticed feature caused us to go over in bandwidth very quickly, disappointing our listeners. I can't imagine a reason that this functionality is necessary, other than someone figured out how to do it and thought it was cool.

**Comment by jonathanbossenger** [comment]
Hi @theGrue 

Thanks for bringing this to our attention. I'm going to check in with the original developer of the plugin, if there's a specific reason it was done this way.

On an unrelated note, but because you mention it in your issue, it's generally not recommended to have allow_url_fopen enabled (see details here http://phpsec.org/projects/phpsecinfo/tests/allow_url_fopen.html), so you might want to check this with your web host.

**Comment by jonathanbossenger** [comment]
@theGrue After chatting with the original developer, the reason the ssp_readfile_chunked function exists is to allow large files to be downloaded, where restrictions exist in the PHP configuration of the web host that would prevent this. 

For your case, may I suggest that we add a filter to the download_file function, that would allow you to change the referrer variable, if it's set to download, and change it to something like 'redirect' which would mean it then defaults to the wp_redirect functionality.

**Comment by theGrue** [comment]
Sounds good, how do we do that?

**Comment by jonathanbossenger** [comment]
@theGrue we've had two other users report possibly related problems on the support forums, so I'm in the process of creating a 'beta' version of the plugin, specific to bypassing this functionality.

Could I ask you to participate in this beta test, by emailing hello@castos.com (marked for my attention) so I can send you the patched version?
