### ISSUE TITLE
feature request: support for "skip to time" in player

### ISSUE THREAD

**Issue by craigconstantine** [CastosHQ/Seriously-Simple-Podcasting#499]
Is there any way to embed GET method data in URLs that would cause SSP to jump the HTML5 player to a particular time code?

(posting this here as requested by Jonathan Bossenger from https://wordpress.org/support/topic/does-ssp-support-skip-to-in-links-to-a-podcast-post/ )

**Comment by craig-constantine** [comment]
<img width="750" alt="Screen Shot 2021-05-17 at 07 22 31" src="https://user-images.githubusercontent.com/2278992/118480794-b32e0800-b6e0-11eb-9fe7-3f7feeb6fd01.png">

Any further thoughts/progress on this? :)

**Comment by craigconstantine** [comment]
Bump! Any chance this feature (support for having the embedded player skip ahead to begin at a particular time) will ever happen in the HTML5 player?
