### ISSUE TITLE
The podcast list block uses GUIDs for links. It should not

### ISSUE THREAD

**Issue by mikelittle** [CastosHQ/Seriously-Simple-Podcasting#527]
**Describe the bug**
The podcast list block uses the post's guid field to generate the href in it's output. It should not do this. the default guid WordPress creates looks like a usable URL but it is not to be used for that. That guid can be modified to, for instance, follow the UUID standards (https://tools.ietf.org/html/rfc4122), in which case it no longer looks like or can act as a URL to the episode. 

**To Reproduce**
1. Add the following code to functions.php. This replaces WordPress' standard guid with a standards compliant UUID.
    ```
    add_filter( 'wp_insert_post_data', function ( $data, $postarr  = array()) {
      if ( '' === $data['guid'] && in_array( $data['post_type'], array( 'post', 'page', 'podcast' ) ) ) {
        $data['guid'] = wp_slash( 'urn:uuid:' . wp_generate_uuid4() );
      }

      return $data;
    } );
    ```
2. Create an episode.
3. Publish the episode
4. Create a page or post and insert the Podcast List block.
5. View the page or post. The links in the generated output look like `urn:uuid:74315850-a2a6-4183-89f8-a5ad1e400a8d` This link has been created from the guid field. They should look like `https://example.com/podcast/podcast-title/`

**Expected behavior**
The links -- title and optional featured image -- in the output of the podcast link should be links to the podcast episodes. 

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - N/A

**Smartphone (please complete the following information):**
 - N/A

**Additional context**
Here is one of the places in WordPress documentation where it explains the GUID should not be used as a link https://developer.wordpress.org/reference/functions/the_guid/

**Comment by jonathanbossenger** [comment]
@mikelittle thanks logging this issue. 

I noticed this myself while working on updates to our blocks recently and I'm in the process of replacing these instances of `guid` with `get_the_permalink()` which as far as I know, is the correct function to use.

**Comment by mikelittle** [comment]
In this case `get_permalink( $episode->ID )` is required. `get_the_permalink()` will retrieve the permalink of the page or post that contains the block rather than the episode being referenced in the block's loop.
