### ISSUE TITLE
Review how episodes are being synced to Castos

### ISSUE THREAD

**Issue by jonathanbossenger** [CastosHQ/Seriously-Simple-Podcasting#557]
**Describe the bug**
At the moment, the admin controller hooks into the post_updated and save_post WordPress actions, to sync an episode to Castos.

It might be worthwhile to review this, and perhaps create a separate class method for the post_updated action vs the save_post action, to help separate each piece of functionality, and send the data via separate actions to Castos.

**Comment by TheCraigHewitt** [comment]
@zahardev and @RobertoGongora let's use this issue to work through how we might set up a queueing system to send episodes to Castos
