### ISSUE TITLE
$this->asset_file is not an array

### ISSUE THREAD

**Issue by goaround** [CastosHQ/Seriously-Simple-Podcasting#563]
```
ErrorException: Notice: Trying to access array offset on value of type null
#8 /plugins/seriously-simple-podcasting/php/classes/blocks/class-castos-blocks.php(81): SeriouslySimplePodcasting\Blocks\Castos_Blocks::register_castos_blocks
```

A look at https://github.com/CastosHQ/Seriously-Simple-Podcasting/blob/master/php/classes/blocks/class-castos-blocks.php#L81 confimes this error. `$this->asset_file` is init https://github.com/CastosHQ/Seriously-Simple-Podcasting/blob/master/php/classes/blocks/class-castos-blocks.php#L27 but set anywhere.

**Comment by jonathanbossenger** [comment]
@goaround thank you for raising this issue. My focus this week is on squashing any bugs from the 2.5.0 update, so I will be sure to include this.
