### ISSUE TITLE
Improving the podcast trash and podcast duplicate process 

### ISSUE THREAD

**Issue by jonathanbossenger** [CastosHQ/Seriously-Simple-Podcasting#572]
**Describe the bug**
At the moment, when a podcast, or podcast enabled post, is trashed, it does not clear the podmotor_ related meta fields
Also, when a podcast, or podcast enabled post, is duplicated, it does not clear those same fields.

**Expected behavior**
When a post is trashed, the podmotor_episode_id should be deleted, but only once the "delete" action has been sent to the Castos API
When a post is duplicated, the podmotor_episode_id should be deleted

**Comment by zahardev** [comment]
@jonathanbossenger I'm not sure about the Delete behavior. Please consider such a test case: the user trashes the podcast, and then decides to restore it. In this case, the podmotor ids will be lost and all the synchronization data will be lost.. So, maybe it's better to remove data from the podmotor and from the database when the post is deleted permanently, not just trashed?

**Comment by jonathanbossenger** [comment]
@zahardev the problem there is that most users only trash the episode in WordPress, and then expect that to mean that it will be trashed in Castos. Because Castos does not have the concept of soft deletes (ie trashed, and then deleted permanently) we have to trigger the Castos delete action when a user trashes an episode in WordPress.

However, what we can do is only delete the podmotor_episode_id, but retain the podmotor_file_id, when the user trashes the episode. 

Then, if they choose to restore it, we should trigger the same `castos_handler::upload_podcast_to_podmotor` method that is fired on saving/updating, so that it recreates the episode in the Castos database, and assigns a new podmotor_episode_id.

Let me know if this makes sense, and I will update the issue description.

**Comment by zahardev** [comment]
@jonathanbossenger Yes, it totally makes sense to me, thanks for clarifying it.

**Comment by jonathanbossenger** [comment]
@zahardev no problem, thanks for bringing up the use case.

**Comment by jonathanbossenger** [comment]
Updated the description based on the discussion.

**Comment by jonathanbossenger** [comment]
@zahardev I'm busy testing this on `release/2.5.4`. When I delete a podcast episode, it does not seem to clear the post meta fields. Could I ask you to test using the same branch, and let me know if I missed a PR?

**Comment by zahardev** [comment]
@jonathanbossenger Yes, l'll test it today.

**Comment by jonathanbossenger** [comment]
Thanks, what I have done so far is trash a post, and then restore it.

It does trigger the delete in Castos, but on restoring, the post meta is still there.

**Comment by jonathanbossenger** [comment]
@zahardev thanks for the updated code, I can see it's deleting the post meta fields.

One small change, can we please update the Admin_Controller@delete_post method to delete the post meta after the `$castos_handler->delete_podcast( $post );` method is called.

A WordPress site won't have those meta fields if it's not connected to Castos, so we can move the delete_post_meta calls to the end of the Admin_Controller@delete_post method.

**Comment by zahardev** [comment]
@jonathanbossenger You're right, deleting meta should go after delete_podcast().

**Comment by zahardev** [comment]
@jonathanbossenger https://github.com/CastosHQ/Seriously-Simple-Podcasting/pull/618
