### ISSUE TITLE
Add a square album image upload to podcast enabled posts

### ISSUE THREAD

**Issue by jonathanbossenger** [CastosHQ/Seriously-Simple-Podcasting#578]
**Describe the bug**
It should be possible to add a podcast specific image to podcasts/podcast enabled posts. Ideally one should upload this in the Podcast Episode specific custom fields.

When the HTML 5 player is rendered, it should attempt to use this image first, and then look for the rest of the possible images for the player.

**Comment by jonathanbossenger** [comment]
@zahardev in testing this fix, using the block editor plugin in WordPress Version 5.6.1, the upload new image button doesn't seem to work. Could you test this and work on a fix, thanks.

The code is currently merged into the `release/2.5.4` branch, so feel free to fix that branch directly.

**Comment by jonathanbossenger** [comment]
@zahardev testing this fix, merged into `release/2.5.4` branch, on WordPress 5.6.1 in the block editor.

The Upload New Image button doesn't seem to trigger anything. If you could please look into this, thanks

Feel free to push your fix straight to the `release/2.5.4` branch

**Comment by zahardev** [comment]
@jonathanbossenger Hm, I can't reproduce this issue, it works for me on WP 5.6.1 and release/2.5.4.

**Comment by jonathanbossenger** [comment]
@zahardev are you using block editor or classic editor?

**Comment by jonathanbossenger** [comment]
@zahardev never mind, seems to be working for me now. thanks
