### ISSUE TITLE
HTML5 Player display on non-audio posts

### ISSUE THREAD

**Issue by SecondLineThemes** [CastosHQ/Seriously-Simple-Podcasting#584]
@jonathanbossenger -

When using the `[ssp_player]` shortcode, if there's no audio-related data added to a post, the HTML5 player still shows.
It should not render if there's no audio file or other metadata associated with a post.

This works as expected with the standard player but not the HTML5 one.

**Comment by jonathanbossenger** [comment]
@SecondLineThemes I'm a little confused as to why you're using the ss_player shortcode on podcast enabled posts without audio, as the shortcode is specifically designed for the purpose of rendering the media player. 

If the standard player doesnt show, that's probably just a function of the wp_audio_shortcode used to render the standard player, than anything else.

**Comment by SecondLineThemes** [comment]
Well, its true that it can be fixed by simply not using the shortcode. However I would also argue that it is probably not ideal to render the media player while there is no source for the audio. 

When the standard player is being used, it doesn't render at all (as expected).
