### ISSUE TITLE
PHP Notice & incorrect enclosure in RSS feed

### ISSUE THREAD

**Issue by dd32** [CastosHQ/Seriously-Simple-Podcasting#608]
**Describe the bug**
The Enclosure included in RSS feeds is invalid, and also produces PHP Notices.

`<enclosure url="https://example.com/2021/01/example.mp3" length="0" type="" />`

PHP Notices are generated by WordPress's feed due to invalid content within the `enclosure` post meta key.

```
E_NOTICE: Undefined offset: 1 in wp-includes/feed.php:494
E_NOTICE: Undefined offset: 2 in wp-includes/feed.php:484
Source: GET https://example.org/podcast/feed/
```

This is caused as the [format of the key by WordPress is expected](https://core.trac.wordpress.org/browser/trunk/src/wp-includes/feed.php?marks=481-494#L473) to be `{URL}\n{Length}\n{File Type}` but is just stored as the plain url: https://github.com/CastosHQ/Seriously-Simple-Podcasting/blob/master/php/classes/controllers/class-admin-controller.php#L902-L937

**To Reproduce**
1. Add a podcast
2. Request a feed containing the podcast.

**Expected behavior**
No PHP Notices, valid `<enclosure` tag.

**Comment by jonathanbossenger** [comment]
Thanks @dd32 will review this in the coming week.
