### ISSUE TITLE
Series taxonomy capabilities

### ISSUE THREAD

**Issue by jonathanbossenger** [CastosHQ/Seriously-Simple-Podcasting#610]
**Describe the bug**
Investigate changing the default capabilities set on the series taxonomy to `edit_podcast`

**Details**
Currently, when the Series taxonomy is created, it uses the default capabilities settings

- 'manage_terms' -> Default 'manage_categories'.
- 'edit_terms' -> Default 'manage_categories'.
- 'delete_terms' -> Default 'manage_categories'.
- 'assign_terms' -> Default 'edit_posts'. 

If a plugin user uses a plugin to create custom user roles (eg Edit Podcasts) then this setting does not allow that user role to edit Series. A workaround is to hook into the ssp_register_taxonomy_args filter and change the `assign_terms` capability to `edit_podcasts`

```
add_filter( 'ssp_register_taxonomy_args', 'set_custom_ssp_tax_args', 10, 2 );
function set_custom_ssp_tax_args( $args, $tax_id ) {
    if ( $tax_id!=='series' ) {
        return $args;
    }
    $args['capabilities']['assign_terms'] = 'edit_podcasts';
    return $args;
}
```

We could consider making this a permanent change, however, we will need to verify that this won't affect the current functionality.

**Comment by jonathanbossenger** [comment]
@TheCraigHewitt this one came out of a support ticket. I'm not 100% sure if this is something we should be doing, but it might be worth investigating.

**Comment by zahardev** [comment]
Done within issue #650
