### ISSUE TITLE
Typo in embed-link generation causes oEmbed

### ISSUE THREAD

**Issue by kaikutzki** [CastosHQ/Seriously-Simple-Podcasting#622]
**Describe the bug**
Hi! I am using the dark mode html5-player.
If you click on "embed" the box with both of the links slides up as it should. But below the embed input type="text"-box there is a wordpress-oEmbed-generated preview of the post. (see screenshot)

![Bildschirmfoto 2021-02-20 um 15 10 51](https://user-images.githubusercontent.com/58510366/108598559-922e7300-738e-11eb-802c-a9b4a2009fbd.jpg)

It seems to be caused by a single quote instead of a double quote (see red mark screenshot)
![Bildschirmfoto 2021-02-20 um 15 11 17](https://user-images.githubusercontent.com/58510366/108598608-dc175900-738e-11eb-8e82-2fb88358d156.jpg)

**Desktop:**
 - OS: Mac OS 10.15.7
 - Browser: Safari 14.0.2
 - Plugin-Version 2.5.3
 - Wordpress 5.6.1

**Comment by jonathanbossenger** [comment]
@kaikutzki thanks for bringing this to our attention. We will investigate further.
