### ISSUE TITLE
Feature Request: Sticky Player with Continuous/Persistent Playback

### ISSUE THREAD

**Issue by KZeni** [CastosHQ/Seriously-Simple-Podcasting#635]
I have also posted this on WP.org for visibility just in case different people are looking in different locations: https://wordpress.org/support/topic/feature-request-sticky-player-with-continuous-persistent-playback/

I was searching around for a podcast player that has a sticky player that then has persistent/continuous playback when navigating pages on a site. I came across https://wordpress.org/support/topic/persistent-player/ where it was mentioned it could be something to look into later on, and I guess I'm curious what the status of that is now.

It'd really be ideal if it was a sticky player that just resumes playback (current audio file, player state, volume, playback position, playlist [potentially], etc.) when navigating (probably just using cookies, right?)

I came across other options that include this functionality, but then they were lacking compared to Seriously Simple Podcasting in other areas. It doesn't seem too ridiculous to propose that SSP could offer this as an official feature of its players (probably having a setting which enables it on a site since placing a shortcode or something to that effect on every page seems like a bit too much to manage on a site.)

SSP really seems like the perfect fit for pretty much everything I need, but it's just missing this one feature. I'd love to be able to use SSP and have it implemented in the most official/supported way possible (which would be realistic if/when this is added). Also, I imagine seamless playback when navigating a website could be utilized by a ton of people that just haven't thought to ask yet (making due with what's offered now while it would be appreciated by them to have added) or otherwise chose a different plugin per this not having that functionality (which could've been seen as vital to them) right now.

Let me know if you want any further info, examples, or anything. Thanks!

**Comment by TheCraigHewitt** [comment]
Hi @KZeni Thanks for the suggestion here.  We have this in the works already and are just working on prioritizing the implementation of this.  Will keep you updated as this progresses along from our end.

**Comment by sebnup** [comment]
Hello all,
Just wondering if this feature update is still underway ?
I've been using SSP for a while now and would really love to see this being implemented !
