### ISSUE TITLE
Player.fm icon is broken on subscribe buttons

### ISSUE THREAD

**Issue by TheCraigHewitt** [CastosHQ/Seriously-Simple-Podcasting#643]
**Describe the bug**
The image/logo for the "player.fm" subscribe button in the Elementor integration is broken and not showing an image.

**To Reproduce**
1. In the wp dashboard in the Podcast -> Options area, enable the `Player.fm` option, and Save those settings.
2. Head to Podcast -> Settings -> Feed Details, and enter some URL in the Player.fm subscribe field.  something like "player.fm" - save those settings
3. Create a page and edit with Elementor.
4. Place the `Subscribe Buttons` Elementor widget
5. See the broken player.fm logo

**Expected behavior**
should show the player.fm logo

**Screenshots**
https://share.getcloudapp.com/6qu8OOon

**Comment by TheCraigHewitt** [comment]
This applies to a lot more listening directories than just player.fm - we are missing at least: 

- Podbean
- Patreon
- Podchaser
- Podbay
- Amazon Music

Probably be best to just match up all of the directories that we display an option for in the Podcast -> Options area and make sure we have a logo for it in the player Subscribe area.

**Comment by zahardev** [comment]
![2021-04-23-b3ad](https://user-images.githubusercontent.com/5578322/115872067-08605c00-a44a-11eb-942d-32bb37586089.png)
