### ISSUE TITLE
Broken notifications

### ISSUE THREAD

**Issue by zahardev** [CastosHQ/Seriously-Simple-Podcasting#645]
**Describe the bug**
Notifications of the plugin are broken

**To Reproduce**
1. Setup the Castos account (Podcast->Settings->Hosting).
2. Update any podcast episode.

**Expected behavior**
- If the episode is successfully uploaded to Castos, it should show the notification "Your episode was successfully synced to your Castos account".
- If uploading to Castos failed, it should show the notification "An error occurred syncing your episode to your Castos account. Please contact Castos support at hello@castos.com.".

**Current behavior**
None of the notifications is shown.

**Comment by TheCraigHewitt** [comment]
@zahardev agree with the wording and the idea of both of these notifications. Where were you planning on displaying the notifications on the page?

**Comment by zahardev** [comment]
I can see them in the code and they should be shown within the default WP notices area. But they are not shown because the page reloads instantly after the update.
