### ISSUE TITLE
Add episode specific image to RSS feed

### ISSUE THREAD

**Issue by zahardev** [CastosHQ/Seriously-Simple-Podcasting#649]
**Describe**
If there is an episode specific image, and it is between 1400x1400px and 3000x3000px in size it should be carried over into the RSS feed as the episode specific image.

**Comment by craig-constantine** [comment]
This also changed the existing behavior. SSP was using a post's WP Featured Image when one wasn't set within SSP's Episode details, https://github.com/CastosHQ/Seriously-Simple-Podcasting/issues/662
