### ISSUE TITLE
Include the option to disable the subscribe and share button in the player.

### ISSUE THREAD

**Issue by MrElliwood** [CastosHQ/Seriously-Simple-Podcasting#658]
The Player template ( /templates/players/castos-player.php ) contains 2 buttons, one to subscribe, and one to share the podcast. I had to manually remove line 45 to 48 to disable these buttons. Can you add an option to show/hide these buttons from the player settings page?

**Comment by MrElliwood** [comment]
I think this works well with the suggestion made in Issue #653

**Comment by zahardev** [comment]
Hi @MrElliwood!
Thanks for the suggestion, this feature will be added in the next plugin version.
