### ISSUE TITLE
2.6.2 Strange code design for how per-episode images are handled

### ISSUE THREAD

**Issue by craig-constantine** [CastosHQ/Seriously-Simple-Podcasting#662]
I had been setting Feature Images on my posts, which SSP was using to populate the `itunes:image` tag in the RSS feed. Upon upgrading from .1 to 2.6.2, all the `itunes:image` tags are no longer set in my RSS feed.

<img width="1701" alt="Screen Shot 2021-04-07 at 06 35 56" src="https://user-images.githubusercontent.com/2278992/113853311-8561b500-976b-11eb-977d-6c8e3bbec74c.png">

I expected the newer feature of setting episode images directly in the SSP "Podcast episode details" would _override_ a featured image. Not that SSP would stop using WP Featured Images entirely. But, ok…

Then I went to "Upload new image" (which doesn't do that, of course. It opens the media library—but, ok) thinking I would simply select the already-uploaded image. (Mind you, I've 100 episodes to do this for.)

But instead, I get this error:

<img width="745" alt="Screen Shot 2021-04-07 at 06 38 37" src="https://user-images.githubusercontent.com/2278992/113853663-e9847900-976b-11eb-9f34-b18f36ca82fc.png">

Why are those dimensions required?
(Those look/feel like Apple's show cover-art dimension. And the error message incorrectly mentions "podcast cover image"—podcast as in the entire show? or the episode? …poor word choice here too.)

I've been happily using 250x250 images for some time. The few places which even use the `itunes:image` field don't seem to care about my smaller dimensions. eg,

<img width="692" alt="Screen Shot 2021-04-07 at 06 49 02" src="https://user-images.githubusercontent.com/2278992/113854918-6d8b3080-976d-11eb-82a7-baa6acdaf4d5.png">

**Comment by zahardev** [comment]
Hi @craig-constantine!
Thanks for reaching out and bringing it to our attention. This restriction will be removed in the next plugin release.
Regards,
Sergey.
