### ISSUE TITLE
Player - subscribe buttons area may be partially hidden

### ISSUE THREAD

**Issue by zahardev** [CastosHQ/Seriously-Simple-Podcasting#675]
**Describe the bug**
If there're a lot of RSS feeds added, they're not shown entirely in the HTML player.

**To Reproduce**
1. Go to Podcast -> Options and select at least 20 services
2. Go to Podcast -> Settings -> Feed details and assign urls for the services
3. Go to the episode page containing the HTML player.
4. Click the Subscribe button

**Expected behavior**
All feed services should be shown

**Current behavior**
Some of the feeds are hidden

**Screenshots**
Current:
![2021-04-23-cfd5](https://user-images.githubusercontent.com/5578322/115856557-51f27c00-a435-11eb-8d2b-a9ffc5752d25.png)

Expected:
![2021-04-23-b3ad](https://user-images.githubusercontent.com/5578322/115856574-55860300-a435-11eb-85d9-8b5d1e65dcb3.png)

**Comment by TheCraigHewitt** [comment]
@zahardev i agree this is how the subscribe option area should look if there are more than 12 directories listed.
