### ISSUE TITLE
Player buttons became very small in some themes

### ISSUE THREAD

**Issue by zahardev** [CastosHQ/Seriously-Simple-Podcasting#679]

**Comment by fbrill** [comment]
@zahardev I'm seeing this where the icons are completely squashed as the height of 18px is ignored... https://staging-beanninjas.kinsta.cloud/blog/podcast/making-business-decisions/ 
![image](https://user-images.githubusercontent.com/5826359/117329573-a0e2dd00-ae49-11eb-93d0-fcce6ce67305.png)
![image](https://user-images.githubusercontent.com/5826359/117329591-a4766400-ae49-11eb-8454-7223f8ac7504.png)

**Comment by fbrill** [comment]
@zahardev - To confirm I was on 2.6.3. and when updating to 2.6.4. it did in fact fix this issue for me.
