### ISSUE TITLE
Elementor Subscribe button widget icons are broken in v2.6.4

### ISSUE THREAD

**Issue by TheCraigHewitt** [CastosHQ/Seriously-Simple-Podcasting#689]
**Describe the bug**
With v2.6.4 the icons for various podcasting directories are broken when using the Elementor "Subscribe Buttons" widget.

**To Reproduce**
1. Install Elementor on the site
2. Create a podcast episode post
3. Add the `Subscribe Buttons` widget
4. See the lack of icons

**Expected behavior**
All icons for various directories (Apple Podcasts, Spotify, Stitcher, etc. should display.  I believe there is just a wrong path when the Elementor widget is trying to pull the image files.

**Screenshots**
![2021-05-06 13_25_22-Podcast Archive - Virtual Summit Mastery - Brave](https://user-images.githubusercontent.com/4099171/117292637-bc151300-ae70-11eb-87db-208d421611c0.png)

See behavior here: https://virtualsummitmastery.com/podcast/1/

**Comment by castos-matt** [comment]
Here's the 403 error https://share.getcloudapp.com/YEuR6dpr

**Comment by zahardev** [comment]
Some images were broken in the previous versions as well. Fixed them too.
