### ISSUE TITLE
Castos Player Block Pulls only Latest 10 Episodes

### ISSUE THREAD

**Issue by KTorrii** [CastosHQ/Seriously-Simple-Podcasting#703]
**Describe the bug**
Castos Player block only provides the option to pull from the latest 10 episodes

**To Reproduce**
1. Go to 'Castos Player. block'
2. Click on 'Select Podcast Episode'
3. See only the latest 10...

**Expected behavior**
A user should be able to select from all of their podcast episodes.

**Comment by TheCraigHewitt** [comment]
@zahardev let's include this in release 2.7.4
