### ISSUE TITLE
Incorrect categories

### ISSUE THREAD

**Issue by TokisanGames** [CastosHQ/Seriously-Simple-Podcasting#705]
According to apple's supported categories, the following categories are incorrect, and at least one gave me trouble with a feed validator. It's not clear if it is case sensitive, so I've listed those: 
https://help.apple.com/itc/podcasts_connect/#/itc9267a2f12

I didn't validate everyone, but here are some that stood out.

Incorrect characters
* Standup -> Stand-Up
* Self Improvement -> Self-Improvement

Case sensitivity
* Non-profit -> Non-Profit
* How to -> How To

php/classes/handlers/class-settings-handler.php

**Comment by ScottDeLuzio** [comment]
Education -> Self Improvement should also be hyphenated
`Education -> Self-Improvement`
