### ISSUE TITLE
Description Formatting lost in RSS Feed

### ISSUE THREAD

**Issue by KTorrii** [CastosHQ/Seriously-Simple-Podcasting#720]
**Describe the bug**
Line breaks from the episode descriptions are being lost in the RSS Feed.

**To Reproduce**
1. Go to an SSP episode page with a full description and show notes, that include line breaks. 
2. Go to the RSS Feed
3. See the line breaks lost. 

**Expected behavior**
The line breaks should carry over. 

**Screenshots**
![image](https://user-images.githubusercontent.com/76892425/119028345-5a2ad200-b975-11eb-9036-9007bcd50587.png)
![image](https://user-images.githubusercontent.com/76892425/119028444-762e7380-b975-11eb-8414-1a3b8cd3a1f6.png)

**Comment by hzlzh** [comment]
The line wrap was missed, we can only roll-back to use the old version of this plugin
![image](https://user-images.githubusercontent.com/1049575/119370859-5f2ab100-bce8-11eb-94b3-5d613bef94fc.png)

![image](https://user-images.githubusercontent.com/1049575/119370829-533eef00-bce8-11eb-8be9-67e292261d36.png)
![image](https://user-images.githubusercontent.com/1049575/119370842-589c3980-bce8-11eb-9c02-f1f061428cfe.png)

**Comment by kaiyoma** [comment]
Any updates here? This is pretty annoying.
