### ISSUE TITLE
Onboarding wizard: The wrong Subcategory is added after selecting option from the menu 

### ISSUE THREAD

**Issue by kimmac00** [CastosHQ/Seriously-Simple-Podcasting#722]
**Describe the bug**
Onboarding wizard > **Podcast Category** screen

After clicking a category in the **Primary Sub-Category** menu, the wrong selection is added. 

**To Reproduce**
1. On the Podcast Category screen > Primary Category > select **Leisure** 
2. Primary Sub-Category > select **Hobbies**
3. See error: **Careers** is the Primary Sub-category added

The same issue occurs when **Society and Culture** is the Primary category and **Personal Journals** is selected as the Subcategory:

![image](https://user-images.githubusercontent.com/77067116/119889733-f2403280-bf04-11eb-8ac3-41b4a1bbeb98.png)

![image](https://user-images.githubusercontent.com/77067116/119889796-06842f80-bf05-11eb-9c91-8438c31cd953.png)

**Comment by zahardev** [comment]
@kimmac00 I can't reproduce this issue. Could you please try it in different browsers (and maybe OS) and check where it can be reproduced?

**Comment by tatasha2004** [comment]
I've reproduced this issue today on Seriously Simple Podcasting v2.17.0.

**Steps**:

1. On the Podcast Category screen > Primary Category > select **Kids&Family**
2. Select Primary Sub-Category **Education for Kids**

Actual result: **Design** Sub-Category is selected
![image](https://user-images.githubusercontent.com/30239355/197955680-6b3fef12-938b-4a1d-98c7-e553d49a927e.png)

Browser: Chrome. MacOS.
