### ISSUE TITLE
Feed prints tags if "Post Content" episode description option is enabled

### ISSUE THREAD

**Issue by zahardev** [CastosHQ/Seriously-Simple-Podcasting#735]
**Describe the bug**
Feed shows tags if "Post Content" episode description option is enabled

**To Reproduce**
1. Go to Podcast -> Feed details -> Default feed page
2. Find "Episode description" option and set it to "Post Content"
3. Go to /feed/podcast/ and see tags (<div>, <img> etc.) in the feed content 

**Expected behavior**
Just text should be shown in the feed content.

![2021-06-14-d50b](https://user-images.githubusercontent.com/5578322/121913113-c6f97800-cd39-11eb-9f75-a20fa513043e.png)

**Comment by KTorrii** [comment]
@zahardev These tags also get sent to the description here at Castos... here is what's in a Castos feed from an episode published with Elementor.

![image](https://user-images.githubusercontent.com/76892425/122426982-b5dd8080-cf5e-11eb-86c6-e87462d37539.png)

**Comment by zahardev** [comment]
https://podnews.net/article/html-episode-notes-in-podcast-rss - decided to strip all tags except <p> there.

**Comment by zahardev** [comment]
![2021-06-24-e9de](https://user-images.githubusercontent.com/5578322/123308544-7994bc00-d52c-11eb-8d32-52e3fe0de42d.png)
![2021-06-24-3005](https://user-images.githubusercontent.com/5578322/123308554-7c8fac80-d52c-11eb-9ca5-167f792df6e9.png)

**Comment by zahardev** [comment]
Decided to not strip <a> tags from the feed.
![2021-06-25-cc25](https://user-images.githubusercontent.com/5578322/123431646-27a67180-d5d2-11eb-86cd-b9727a7c3b3f.png)
