### ISSUE TITLE
Revise text when uploading an episode file 

### ISSUE THREAD

**Issue by kimmac00** [CastosHQ/Seriously-Simple-Podcasting#738]
**Describe the bug**
Improve consistency and reduce confusion by revising text when a creator is ready to upload a new episode file. 

**To Reproduce**
1. Go to Podcast > Add New
2. Text and button label related to uploading an episode file refers to uploading a "podcast file"

![image](https://user-images.githubusercontent.com/77067116/122474709-9a3f9d80-cf91-11eb-8d75-5e92afdc2db3.png)

Heading: Podcast file:
Revise: Episode file (no colon)

Button label: Select podcast file
Revise: Select file

Help text: Upload the primary podcast file or paste the file URL here.
Revise: Upload audio episode files as MP3 or M4A, video episodes as MP4, or paste the file URL

**Comment by zahardev** [comment]
@kimmac00 Good point, will make the changes. The only thing I'm not sure about is no colon for Episode file since other settings do have a colon.
![2021-06-24-4cbc](https://user-images.githubusercontent.com/5578322/123253491-361f5b00-d4f6-11eb-8630-e5214b12b452.png)
What do you think?

**Comment by kimmac00** [comment]
@zahardev The colon is really more of a personal UX writing style than a best practice. If keeping the colon is more consistent with the rest of the UI then we should definitely keep it. Good call
