### ISSUE TITLE
Option to Modify Series URL Structure

### ISSUE THREAD

**Issue by KTorrii** [CastosHQ/Seriously-Simple-Podcasting#743]
Currently, SSP doesn't include the Series name in the Episode URL structure which is problematic for SEO. 

`https://mysite.com/podcast/episode-name`

Perhaps we can add an option that can be enabled to include the series name within the episode URL structure. 

`https://mysite.com/podcast/series-name/episode-name`

**Comment by zahardev** [comment]
@TheCraigHewitt It will take some time to implement that feature. What do you think, do we need it as the basic plugin functionality?

**Comment by TheCraigHewitt** [comment]
Hi @zahardev I think that implementing the two suggestions here: https://feedback.castos.com/suggestions/190506/urgent-series-podcasts-rss-and-schema-links-are-wrong would cover much of what we're looking to accomplish with this.  

If we're able to make those two updates I think it'd be helpful.
