### ISSUE TITLE
Enclosure file type is image/jpeg instead of audio/mpeg.

### ISSUE THREAD

**Issue by KTorrii** [CastosHQ/Seriously-Simple-Podcasting#753]
**Describe the bug**
Reviewed with Sergey already but it appears that some MP3 files are being classified as type="image/jpeg" in the enclosure URL as opposed to type="media/mpeg". This is causing those episodes to be ignored by platforms such as Spotify that require that enclosure type of media/mpeg.

**Comment by zahardev** [comment]
Couldn't reproduce it for now, will get back to it later.
