### ISSUE TITLE
Reusable blocks have disappeared from feed

### ISSUE THREAD

**Issue by craigconstantine** [CastosHQ/Seriously-Simple-Podcasting#755]
**Describe the bug**
updated 273 from whatever the release was before that. I do a before/after capture of the feed so I can diff.

The contents of a reusable block that I add to the body of my podcast-type posts no longer appears in the feed file.

**To Reproduce**
Set up a resuable block. Add it to the body of a post. Look at the generated feed from the two versions.

I'm attaching the before/after files of my full feed…
[20210727.txt](https://github.com/CastosHQ/Seriously-Simple-Podcasting/files/6895938/20210727.txt)
[20210728.txt](https://github.com/CastosHQ/Seriously-Simple-Podcasting/files/6895939/20210728.txt)

**Comment by zahardev** [comment]
Hi @craigconstantine!
Thanks for bringing it to our attention, I'll try to reproduce the issue. Meanwhile, you can try to install the WP Rollback plugin (https://wordpress.org/plugins/wp-rollback/) and revert to version 2.7.2.

**Comment by craigconstantine** [comment]
Thanks!

**Comment by craigconstantine** [comment]
This was fixed in 2.7.4 :)  Thank you!
