### ISSUE TITLE
howler.js as a replacement for wp_audio_shortcode()

### ISSUE THREAD

**Issue by whyisjake** [CastosHQ/Seriously-Simple-Podcasting#85]
Just saw this JS library, and thought it might be cool to extend the default audio shortcode widget to be something, you know, a little better...

http://goldfirestudios.com/blog/104/howler.js-Modern-Web-Audio-Javascript-Library

**Comment by whyisjake** [comment]
This could be a standalone plugin. One of the nice things about SSP is the lack of a heavily styled player.

**Comment by hlashbrooke** [comment]
That is cool actually. I think the best way forward would be a separate plugin that would work with or without SSP, but built with SSP in mind. That's what I did with the Media Player Style Kit that I released a little while ago: https://wordpress.org/plugins/media-player-style-kit/ - but I think the howler.js library would be a cool WP plugin for sure.
